### PR TITLE
newbranch

### PR DESCRIPTION
**Pull request by adam731**

### CODE REVIEW

**Review by julia-parewick — APPROVED** [review]
good good

**Review by MasonSeward1 — CHANGES_REQUESTED** [review]
Change the class name to represent what it is trying to test. Alternatively, setup main methods in each individual class to test that class and what it should do, such as @julia-parewick has done in other classes.

**Comment by djlew89** [comment]
> Change the class name to represent what it is trying to test. Alternatively, setup main methods in each individual class to test that class and what it should do, such as @julia-parewick has done in other classes.

Yeah, one of the ways we can do this is to have a test package that contains all the tests we want to run. I don't mind having one test class right now just to make sure we can prove everything works and expand on it after demos.

**Review by djlew89 — APPROVED** [review]
Looks like a good start

**Review by DANCON1 — APPROVED** [review]
Looks good!

**Review by MasonSeward1 — APPROVED** [review]

**Pull request merged**
