### PR TITLE
Initial Interface commit

### PR DESCRIPTION
**Pull request by MasonSeward1**
- Added interface class
- Added option to create user
- Added functionality to connect to database
- Added functionality to add user to database
- Added constructor to Driver class
- More

### CODE REVIEW

**Review by julia-parewick — APPROVED** [review]
nice

**Review by djlew89 — APPROVED** [review]
Solid work

**Review by adam731 — APPROVED** [review]
looks good i'm assuming src/ApplicationUI.java is going to need some more error handling added to it once we dive deeper into the application development

**Comment by DANCON1** [comment]
Looks good

**Pull request merged**
